nginx:
  image: chayka/php-server
#  build: .
  container_name: chayka-php-server
  restart: unless-stopped
  ports:
    - "80:80"
    - "443:443"
    # - "9000:9000"
  links:
    - mariadb:mysql
    # - memcached:memcached
    # - redis:redis
  volumes:
    - /var/www:/var/www
    # - /var/lib/mysql:/var/lib/mysql
    # - ./sites:/etc/nginx/conf.d

mariadb:
  image: mariadb
  container_name: chayka-mysql-server
  restart: unless-stopped
  ports:
    - "3306:3306"
  environment:
    MYSQL_ROOT_PASSWORD: Str0ngPassword
#   volumes:
#     - /var/lib/mysql:/var/lib/mysql

# memcached:
#   image: memcached
#   ports:
#     - "11211:11211"

# redis:
#   image: redis
#   ports:
#     - "6379:6379"
